global:
  slack_api_url: 'https://hooks.slack.com/services/SECRET/SECRET'
  smtp_require_tls: false
  smtp_from: 'Alertmanager <AlertOtt@otus.io>'
  smtp_smarthost: 'smtp:25'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_hello: 'otus.io'


route:
  receiver: 'slack-notifications'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname]
  routes:
    - receiver: 'email-notifications'
      match_re:
          severity: page|warning


receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksandr-chudakov'
- name: 'email-notifications'
  email_configs:
    - to: 'chudo88@gmail.com'
      send_resolved: true
      require_tls: false
