version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
      - back_net
  post:
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      - back_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      - back_net

volumes:
  post_db:


networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
