{
 "title": "Docker and system monitoring telegraf",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": { "query": "label_values(container_group)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 13, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(docker_container_net_rx_bytes{container_name=~\".*\"}[$interval])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(docker_container_net_tx_bytes{container_name=~\".+\"}[$interval])) by (container_name)",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(docker_container_cpu_usage_percent{container_name=~\".+\"}[$interval])) by (container_name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=~\".+\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum(docker_container_mem_limit{container_name=~\".+\"}) by (container_name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(docker_container_mem_usage{container_name=~\".+\"}) by (container_name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}