---
# tasks file for roles/k8s_worker

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  delegate_to: "{{ item }}"
  with_items: "{{ groups['k8s_master'] }}"

- name: dubug
  debug:
    msg: "{{ join_command_raw.results[0].stdout }}"

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.results[0].stdout }}"


- name: add worker to cluster
  shell: "{{join_command}} >> worker_setup.txt"
  args:
    chdir: "{{ ansible_facts.user_dir }}"
    creates: worker_setup.txt
