---
service:
  internalPort: 9292
  externalPort: 9292

image:
  repository: iudanet/ui
  tag: latest

ingress:
  class: nginx
  # domain: gitlab-k8s.iudanet.com

postHost:
postPort:
commentHost:
commentPort:
