---

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python-pip
    # - python-docker
    - python3-pip
    # - python3-docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo:  deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
  loop:


- name: Install Docker Module for Python
  pip:
    name:
    - docker
    # - docker-py
    executable: pip

- name: Install Docker Module for Python
  pip:
    name:
    - docker
    # - docker-py
    executable: pip3

- name: Enable Docker Service
  service:
    name: docker
    state: started
    enabled: yes
