name: linter-pr
on:
  pull_request:
    branches:
      - main

jobs:
  otus-homeworks:
    runs-on: ubuntu-latest
    container: express42/otus-homeworks:0.7.1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: express42/otus-homeworks
          path: otus-homeworks
          ref: 2020-11
      - name: Get versions
        run: 'echo -=Get versions=-; ansible --version; ansible-lint --version; packer version; terraform version; tflint --version; docker version; docker-compose --version'
      - name: run test otus
        run: cd  $GITHUB_WORKSPACE && ./otus-homeworks/homeworks/${GITHUB_HEAD_REF}/run.sh
